version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/sugarcrm:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'sugarcrm_data:/bitnami/sugarcrm'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  sugarcrm_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
